import images from "./images";

export const projects = [
  {
    id: "bizz-buzz",
    title: "Bizz Buzz",
    heroDesc:
      "I help startups and series A—D teams to establish a strong connection between their product and customers",
    problem:
      "Entrepreneurs face numerous challenges in today's competitive business landscape. Limited access to a centralized platform for networking and collaboration hinders their ability to connect, share ideas, and form strategic partnerships. Existing social media platforms lack a dedicated space tailored to the unique needs of entrepreneurs, making it difficult for them to harness the full potential of their networks and scale their ventures effectively.",
    solution:
      "Bizz Buzz is a groundbreaking social media platform designed specifically for entrepreneurs, addressing the aforementioned challenges head-on. It offers a range of features, including industry-specific groups, resource sharing, project collaboration tools, and tailored matchmaking algorithms, fostering meaningful connections and facilitating valuable collaborations within the entrepreneurial community.",
    longDesc:
      "From its inception, Bizz Buzz aimed to revolutionize the way entrepreneurs network and collaborate. Inspired by the struggles faced by entrepreneurs in their personal journeys, the platform's founders embarked on a mission to create a solution that would empower entrepreneurs worldwide. They envisioned a space where like-minded individuals could come together, share experiences, exchange knowledge, and forge partnerships that transcend traditional boundaries.\n\nBizz Buzz's journey began with a small team of dedicated individuals who believed in the power of entrepreneurship and the impact it could have on the world. They meticulously analyzed the pain points faced by entrepreneurs, conducting in-depth market research and engaging with the community to understand their needs. Armed with this knowledge, they set out to build a social network that would bridge the gap between entrepreneurs and provide them with a supportive ecosystem.",
    year: "2023",
    timeframe: "16 days",
    tools: "React, Node.js, Docker",
    category: "Personal Project",
    image: images.project1,
    bgColor: "#ff6200ff",
    textColor: "#000",
    seeAlso: ["aquaflow", "snackify", "zengo", "roverride"],
  },
  {
    id: "aquaflow",
    title: "aquaflow",
    heroDesc: "Creating seamless branding and identity experiences.",
    problem: "Brands struggle to maintain visual consistency.",
    solution: "A unified design system and branding package.",
    longDesc:
      "Aquaflow represents a deep dive into modern branding requirements.",
    year: "2023",
    timeframe: "30 days",
    tools: "Figma",
    category: "Branding and Identity",
    image: images.project4,
    bgColor: "#ffffff",
    textColor: "#1f00ff",
    seeAlso: ["bizz-buzz", "snackify", "zengo", "roverride"],
  },
  {
    id: "snackify",
    title: "snackify",
    heroDesc: "Enhancing user experience for a fast-paced delivery app.",
    problem: "Users take too long to order snacks.",
    solution: "A streamlined, intuitive UI that reduces friction.",
    longDesc:
      "Snackify focuses heavily on UI/UX principles to optimize the ordering flow.",
    year: "2023",
    timeframe: "21 days",
    tools: "React Native",
    category: "UI/UX",
    image: images.project3,
    bgColor: "#96d3b2",
    textColor: "#000",
    seeAlso: ["bizz-buzz", "aquaflow", "zengo", "roverride"],
  },
  {
    id: "zengo",
    title: "zengo",
    heroDesc: "A personal project exploring bold aesthetic choices.",
    problem: "Finding the right visual balance.",
    solution: "Using vibrant yellow paired with dark contrasts.",
    longDesc: "Zengo is an exploration in high-contrast visual design.",
    year: "2024",
    timeframe: "14 days",
    tools: "Next.js",
    category: "Personal Project",
    image: images.project2,
    bgColor: "#ffe300",
    textColor: "#3d3b54ff",
    seeAlso: ["bizz-buzz", "aquaflow", "snackify", "roverride"],
  },
  {
    id: "roverride",
    title: "roverride",
    heroDesc: "Refining identity for an automotive startup.",
    problem: "Startup lacked a distinctive identity.",
    solution: "A comprehensive brand system with dark, sleek tones.",
    longDesc:
      "Roverride combines elegance with cutting-edge automotive aesthetics.",
    year: "2023",
    timeframe: "45 days",
    tools: "Figma, Framer",
    category: "Branding and Identity",
    image: images.project5,
    bgColor: "#3d8bffff",
    textColor: "#ffffffff",
    seeAlso: ["bizz-buzz", "aquaflow", "snackify", "zengo"],
  },
];
